// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyJ6p5W7ppGUhk8eD2eqYefRY3xqGn7Rs',
    appId: '1:70994060664:web:2565b2fb3ff7dbfa00548d',
    messagingSenderId: '70994060664',
    projectId: 'alpha-website-84291',
    authDomain: 'alpha-website-84291.firebaseapp.com',
    storageBucket: 'alpha-website-84291.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTG2xSetpxljHSveJg5ZjV9PWqgCkYG30',
    appId: '1:70994060664:ios:c1af044d415ba3ba00548d',
    messagingSenderId: '70994060664',
    projectId: 'alpha-website-84291',
    storageBucket: 'alpha-website-84291.appspot.com',
    iosBundleId: 'com.alfa.com.alfa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTG2xSetpxljHSveJg5ZjV9PWqgCkYG30',
    appId: '1:70994060664:ios:c1af044d415ba3ba00548d',
    messagingSenderId: '70994060664',
    projectId: 'alpha-website-84291',
    storageBucket: 'alpha-website-84291.appspot.com',
    iosBundleId: 'com.alfa.com.alfa',
  );
}
